### ISSUE TITLE
Export to USDZ

### ISSUE THREAD

**Issue by supersglzc** [gkjohnson/three-bvh-csg#115]
Thanks for the amazing repo!

After several operations, I try to export the scene to a USDZ file using USDZ exporter. One issue I encounter is that the material of each mesh is actually an array of MeshStandardMaterial, however, the USDZ exporter can only take MeshStandMaterial rather than an array. 

Is there any way to fix this so we can export the mesh?

Thanks!

**Comment by gkjohnson** [comment]
The produced mesh is just a three.js object so you can set the mateial to be whatever you want afterward. Or, as the docs state, you can set the [useGroups](https://github.com/gkjohnson/three-bvh-csg#usegroups) field to disable the generation of a multimaterial geometry.

**Comment by supersglzc** [comment]
I try to set the useGroups to false, however, it will generate a mesh without any material. 

Also, is there any way that can merge the array of materials? I want the mesh to be the same, so I think I still want to use the current array of materials.

**Comment by gkjohnson** [comment]
> I try to set the useGroups to false, however, it will generate a mesh without any material.

This isn't the case. It generates a mesh with the single material used by the first brush.

> Also, is there any way that can merge the array of materials? I want the mesh to be the same, so I think I still want to use the current array of materials.

This depends on the differences between the materials used. If you have general three.js questions about how to handle and process objects or materials I'd ask at the [forum](https://discourse.threejs.org/)

**Comment by supersglzc** [comment]
Thanks for the response. After I assign the original material to the new brush, everything works fine.

I know this might be irrelevant to the repo, just curious if you know any good way to add joints/articulations in three.js and export it to usdz or any other file formats?

**Comment by gkjohnson** [comment]
> I know this might be irrelevant to the repo, just curious if you know any good way to add joints/articulations in three.js and export it to usdz or any other file formats?

Again if you have general three.js questions pleas use the forum. Unfortunately I don't have the bandwidth for general three.js support on tangential topics.
