### ISSUE TITLE
Unable to create a Brush with a geometry

### ISSUE THREAD

**Issue by Micolho** [gkjohnson/three-bvh-csg#117]
I am currently using v0.0.4 and i am unable to create a brush using the mesh constructor! This issue happens if you use the following import as documented on the [README](./README.md)
```
import { Brush} from 'three-bvh-csg';
```

After some time messing around, I found out that the declaration of a Brush in [index.d.ts](./src/README.md) is missing out on the constructor, which then procedes to give me errors while compiling, saying that constructor expected 0 arguments and got 2 (geometry and material)!

The code works well if i explicit do the following import
```
import { Brush } from 'three-bvh-csg/src/core/Brush.js';
```

**Comment by gkjohnson** [comment]
I am not a typescript expert but is there something I'm not understanding? `Brush` directly extends `Mesh` so their should be no need to provide an explicit constructor since it should inherit the parent class constructor:

```ts
export class Brush extends Mesh {

  isBrush: boolean;
  markUpdated(): void;
  isDirty(): boolean;
  prepareGeometry(): void;
  disposeCacheData(): void;

}
```

**Comment by frading** [comment]
if I may, the types seem correct to me. The Brush is expected to be created with 2 args, the geometry and an optional material, just like a Mesh.
@Micolho you can see how I've used it in typescript here: https://github.com/polygonjs/polygonjs/blob/master/src/engine/operations/sop/Boolean.ts#L64
