### ISSUE TITLE
uv attribute is undefined

### ISSUE THREAD

**Issue by Innovgame** [gkjohnson/three-bvh-csg#118]
TypeError: Cannot read properties of undefined (reading 'array')

![image](https://github.com/gkjohnson/three-bvh-csg/assets/38150357/7a8e7071-e392-4eeb-a155-88857e2b735f)

**Comment by Innovgame** [comment]
My model does not have uv attribute set.

**Comment by gkjohnson** [comment]
From the docs:
> All geometry are expected to have all attributes being used and of the same type.
