### ISSUE TITLE
Not supported with three@"^0.153.0"

### ISSUE THREAD

**Issue by oxsmose** [gkjohnson/three-bvh-csg#120]
Could not resolve dependency:
npm ERR! peer three@"^0.144.0" from three-bvh-csg@0.0.7
npm ERR! node_modules/three-bvh-csg
npm ERR!   three-bvh-csg@"*" from the root project

**Comment by gkjohnson** [comment]
Likely because the peer dependency should be `>=0.144.0` - feel free to make a PR with the change.
