### ISSUE TITLE
When the object used for detection is a reverse cube, how can csg detection be performed correctly

### ISSUE THREAD

**Issue by letmestady** [gkjohnson/three-bvh-csg#126]
![image](https://github.com/gkjohnson/three-bvh-csg/assets/116178387/14f8424b-7c7d-4f55-a89d-9e3bc3d64440)
Initial state

![image](https://github.com/gkjohnson/three-bvh-csg/assets/116178387/cc63803e-9d6f-454a-ab51-d1a43941b791)
As shown in the figure above, after cutting, the object to be cut is a standard cube, and the cube with the material is the reverse side, which occurs when csg is performed on the reverse side. csg doesn't support tails?

**Comment by gkjohnson** [comment]
What are you expecting to happen here?

> csg doesn't support tails?

I don't know what this means

**Comment by letmestady** [comment]
> 你期待在这里发生什么？该项目不支持反转几何体。
> 
> > csg不支持tails吗？
> 
> 我不知道这意味着什么

I want this effect
![1690959081776](https://github.com/gkjohnson/three-bvh-csg/assets/116178387/af939048-32d2-4d04-baa0-2c250dcca625)
But this cube is in reverse，Is that possible?
![image](https://github.com/gkjohnson/three-bvh-csg/assets/116178387/6ae6695e-3ce6-4a7d-8852-218f0faa57ea)

**Comment by gkjohnson** [comment]
As I've said. Inverted geometry is not supported. If you want to cut a hole in another geometry you must you the "SUBTRACT" operation.
