### ISSUE TITLE
Cannot find name 'Line'. Did you mean 'Line3'?

### ISSUE THREAD

**Issue by joe-shajan** [gkjohnson/three-bvh-csg#128]
Why I'm getting this error?

![image](https://github.com/gkjohnson/three-bvh-csg/assets/69904519/a981cb00-7c10-432b-b9c3-a17a65e70842)

**Comment by gkjohnson** [comment]
Yes it looks like it's supposed to be "Line3". Thanks for the catch. Would you like to make a PR?

**Comment by joe-shajan** [comment]
@gkjohnson raised new PR 🚀
