### ISSUE TITLE
Bad geometry after CSG operation

### ISSUE THREAD

**Issue by samevision** [gkjohnson/three-bvh-csg#130]
Hello,

I am doing some experiments with CSG. My goal is to edit an object with different operations and export the resulting mesh (STL). Unfortunately, however, Geometry is not usable further.

In the following example I want to cut a cylinder out of a bevelled cube. In the picture you can see on the left the geometry of the object generated with three.js and on the right the same one I created in Blender.

![screenshot](https://i.ibb.co/QDtdMMC/Screenshot-2023-08-17-at-11-13-28.png)

The circle was not really cut out. In three.js it is shown like that, but the geometry is not really like it should be.

Is there any way to fix this?

Thanks.

Best

**Comment by sonygod** [comment]
Your question has nothing to do with CSG. In Blender, CSG might come with a series of optimizations, such as optimizing UV and converting triangles into quads. Are you mainly concerned with calculating the UV corresponding to triangles?
<img width="579" alt="image" src="https://github.com/gkjohnson/three-bvh-csg/assets/748320/ecd7dab3-710f-489b-bfb7-e09dea833819">

**Comment by samevision** [comment]
Did you create the cube of your screenshot with three-bvh-csg? Please export the cube to STL (https://threejs.org/docs/#examples/en/exporters/STLExporter) and import the stl file into blender. You'll see that the cube will look like the one of my initial screenshot. The hole is not really cutted into the cube.

**Comment by gkjohnson** [comment]
The STLExporter is not maintained in this project so this is not really the right place to ask why it's not exporting the geometry as it's rendered. The [discourse forums](https://discourse.threejs.org/) or three.js discord may be better places to ask.

That said the resulting csg geometry uses the Geometry.groups and Geometry.drawRange fields to update the geometry without creating a completely new one. It's been found that the [GLTFLoader does not respect drawRange](https://discourse.threejs.org/t/gltfexporter-does-not-respect-drawrange/51881/5) so STLExporter may have the same issue.

**Comment by samevision** [comment]
Oh, I see. That’s the same issue for sure. Thanks for this information!

You said: „It might be nice to provide a transform function in BufferGeometryUtils to convert draw range geometry so it can be exported correctly.“

I know it’s not related to this package. But is it a lot of work to solve this? It would be really nice to export the manipulated objects correctly.

**Comment by gkjohnson** [comment]
> I know it’s not related to this package. But is it a lot of work to solve this? It would be really nice to export the manipulated objects correctly.

It's not complicated but you'll have to understand to understand the drawRange and groups fields and what they're doing. And you should look into what the issue is with the STLExporter before to make sure it will actually fix the issue.

> I assume it’s better to extend the exporter instead of creating a new geometry on each operation to keep performance as high as possible.

You can already see in that thread that that was rejected. Maybe dependency on drawRange can be removed if performance isn't impacted (#131). Feel free to do some tests if you'd like to help.
