### ISSUE TITLE
Two THREE.BoxGeometry intersect error.

### ISSUE THREAD

**Issue by kxh4892636** [gkjohnson/three-bvh-csg#145]
The example code is as follows.

```typescript
import { BoxGeometry, BufferGeometry, PlaneGeometry } from 'three'
import { Brush, Evaluator, INTERSECTION } from 'three-bvh-csg'

const intersection = (
  geometry1: BufferGeometry,
  geometry2: BufferGeometry,
): BufferGeometry => {
  const brush1 = new Brush(geometry1)
  const brush2 = new Brush(geometry2)

  const csgEvaluator = new Evaluator()
  const result = csgEvaluator.evaluate(brush1, brush2, INTERSECTION)

  return result.geometry
}

const geo1 = new BoxGeometry(10, 10, 10)
const geo2 = new PlaneGeometry(10, 10)
geo2.translate(0, 0, 5)
const geo3 = new BoxGeometry(10, 10, 10)
geo3.translate(0, 0, 10)

const intersection1 = intersection(geo1, geo2)
const intersection2 = intersection(geo1, geo3)
console.log(intersection1.getAttribute('position'))
console.log(intersection2.getAttribute('position'))
```

The bottom surface of geo3 is the same as geo2, but when the two BoxGeometry intersect, the result is null. However, when BoxGeometry intersects with PlaneGeometry, the result is correct.

The result is as follows.

```
BufferAttribute {
  isBufferAttribute: true,
  name: '',
  array: Float32Array(18) [
    -5, 5,  5, -5, -5, 5,  5,
     5, 5, -5, -5,  5, 5, -5,
     5, 5,  5,  5
  ],
  itemSize: 3,
  count: 6,
  normalized: false,
  usage: 35044,
  updateRange: { offset: 0, count: -1 },
  gpuType: 1015,
  version: 1
}
BufferAttribute {
  isBufferAttribute: true,
  name: '',
  array: Float32Array(0) [],
  itemSize: 3,
  count: 0,
  normalized: false,
  usage: 35044,
  updateRange: { offset: 0, count: -1 },
  gpuType: 1015,
  version: 1
}
```

**Comment by gkjohnson** [comment]
Please provide a live example with something like jsfiddle and pictures of the issue

**Comment by gkjohnson** [comment]
Again - please provide pictures and explain what you expect. If you look at this there's nothing incorrect about the result. The result of an intersection of two shapes in a just-touch configuration has no volume and therefore no shape.

<img width="477" alt="image" src="https://github.com/gkjohnson/three-bvh-csg/assets/734200/986dddcc-01e7-4d1d-8842-07093e88b56b">

> However, when BoxGeometry intersects with PlaneGeometry, the result is correct.

Using PlaneGeometry is not valid since it is not two manifold and has no volume.
