### ISSUE TITLE
Getting different results after upgrading from v0.0.10 to v0.0.11

### ISSUE THREAD

**Issue by danielesteban** [gkjohnson/three-bvh-csg#173]
I having some different results with the same operations after upgrading to v0.0.11 this morning.

I tried to reduce it into the smallest example to reproduce what I mean.
Here you can test by swapping the three-bvh-csg imports at the top:
https://glitch.com/edit/#!/flawless-adventurous-server?path=script.js

Here's with v0.0.10:
![image](https://github.com/gkjohnson/three-bvh-csg/assets/806111/e2419148-22eb-4629-9105-70fec97254bd)

Here's with v0.0.11:
![image](https://github.com/gkjohnson/three-bvh-csg/assets/806111/b3d27c07-e823-4d68-b333-ceabeb9390f3)

**Comment by gkjohnson** [comment]
Hello! Thanks for he report - I'm unable to open the glitch for some reason (it just says error starting the error). Can you use something like jsfiddle, instead?

Also if you can help find which commit caused the error that would help narrow down how to fix the issue.

**Comment by gkjohnson** [comment]
Thanks!

> Or is it the only choice to download the repo, go commit by commit building and testing it out?

Yes right now you'd have the pull the repo and do something like a git bisect from v0.0.10 to v0.0.11. If not I'll be able to get to it - but I appreciate the help!

**Comment by danielesteban** [comment]
Aight.. I think I tracked it down.

With the previous https://github.com/gkjohnson/three-bvh-csg/commit/f50feeacfab86bfc9f138c6d48c9c7e59e577b64:
![image](https://github.com/gkjohnson/three-bvh-csg/assets/806111/c3c720de-dab4-4fcb-8aaa-94623843e8d1)

But from this one onwards: https://github.com/gkjohnson/three-bvh-csg/commit/5009a216b9e1c8b2bc4268e84e17ae66cc82982c
![image](https://github.com/gkjohnson/three-bvh-csg/assets/806111/d32e0183-1971-45f3-9627-ee1435d7f182)

**Comment by danielesteban** [comment]
I uploaded the repo I used to test this to: https://github.com/danielesteban/csgtest

```bash
git clone --recursive https://github.com/danielesteban/csgtest.git
cd csgtest
pnpm install
pnpm start
# Open: http://localhost:8080/

# If you do this it works as intended
cd three-bvh-csg/
git checkout f50feeacfab86bfc9f138c6d48c9c7e59e577b64
```

**Comment by danielesteban** [comment]
Nice. That was quick!
Just to confirm that this one did the trick: https://github.com/gkjohnson/three-bvh-csg/commit/44025fe99ca703a12f84a08d268da3d9a2320510
![image](https://github.com/gkjohnson/three-bvh-csg/assets/806111/2490299b-f9d5-4e16-9bd6-963b1f1b0c88)
Should I close the issue or do you want me to wait until it hits an npm release?

**Comment by gkjohnson** [comment]
Thanks! Got it fixed in #176 and just published a new version.

**Comment by gkjohnson** [comment]
Sorry missed your last message -

> Just to confirm that this one did the trick: 44025fe99ca703a12f84a08d268da3d9a2320510

Yeah this is the commit. It was using the same ray direction for every raycast to test containment previously which could cause problems the triangle was coplanar.

**Comment by danielesteban** [comment]
No worries.

I'm sorry but I found another bug/issue.. not sure if related but it happens rigth after: 
https://github.com/gkjohnson/three-bvh-csg/commit/5009a216b9e1c8b2bc4268e84e17ae66cc82982c

I just added a cone at the bottom of the base.
Here's with v0.0.12:
![image](https://github.com/gkjohnson/three-bvh-csg/assets/806111/33aaab9e-16de-46f0-b9f3-46367bd5eb37)

Here's with https://github.com/gkjohnson/three-bvh-csg/commit/f50feeacfab86bfc9f138c6d48c9c7e59e577b64:
![image](https://github.com/gkjohnson/three-bvh-csg/assets/806111/8f39e09b-4ac5-435d-b03c-07a416228c61)

I updated the example repo at: https://github.com/danielesteban/csgtest
And the jsfiddle: https://jsfiddle.net/9kLhuqn1/3/

**Comment by gkjohnson** [comment]
Thanks - can you make another issue? I'll have to take a look ater.
