### ISSUE TITLE
Hollow Subtraction Regression v0.0.12

### ISSUE THREAD

**Issue by jteppinette** [gkjohnson/three-bvh-csg#179]
When using `HOLLOW_SUBTRACTION` on `v0.0.12` I am seeing a regression (from `v0.0.11`). My result seems to have a much larger bounding box. I am assuming there are some floating vertices somewhere.

I can diagnose more in a bit, but wanted to go ahead and add this.

**Comment by gkjohnson** [comment]
Please provide a JS Fiddle demonstrating the issue.

**Comment by gkjohnson** [comment]
We can reopen when there's a demonstration of the problem.
