### ISSUE TITLE
Orphaned Triangles After Operation

### ISSUE THREAD

**Issue by JakeDluhy** [gkjohnson/three-bvh-csg#183]
I believe this may be related to #182, as it may explain the larger bounding box. I am exploring using `three-bvh-csg` with React and have built up a scene where I extrude a shape and then cut off the bottom (don't get me started on extrude geometry not having a single side option). It looks great:
![Screenshot 2023-12-01 at 10 40 30 AM](https://github.com/gkjohnson/three-bvh-csg/assets/6790323/7689dcef-dfa1-4a31-b0a3-6f133e4ddf26)

I also want to export to an STL, however when I do that there are some weird things that show up. In short, when I add it to blender I am able to see the issue:
![Screenshot 2023-12-01 at 10 38 01 AM](https://github.com/gkjohnson/three-bvh-csg/assets/6790323/2507aa8c-ede0-4cad-a174-05cdfac97206)

There are some orphaned triangles in a very weird way. It kind of looks like they're in the shape of a projection of the first object (extruded shape) onto the second one (a large box geometry underneath). Here's another example:
![Screenshot 2023-12-01 at 9 05 28 AM](https://github.com/gkjohnson/three-bvh-csg/assets/6790323/f0c6beea-84f8-4c6b-8bdd-a0593b04c3ce)

I created a minimal reproduction using just JS here: https://codepen.io/jakedluhy/pen/YzBJgPp. I didn't create an actual THREE scene, since the scene itself looks fine. Let me know if you would like me to add that.

EDIT: One more detail - all of those orphaned triangles all have the exact same point for the vertices

**Comment by gkjohnson** [comment]
Thanks for the details!

> I didn't create an actual THREE scene, since the scene itself looks fine. Let me know if you would like me to add that.

It would be useful to add a simple scene with a bounding box to inspect the issue more easily.

**Comment by gkjohnson** [comment]
Yes looks like there are extra points being added:

<img width="250" alt="image" src="https://github.com/gkjohnson/three-bvh-csg/assets/734200/0449c971-3114-4e50-8ec3-61bd92e65f3a">

The same thing seems to happen with ADDITION and DIFFERENCE:

<img width="250" alt="image" src="https://github.com/gkjohnson/three-bvh-csg/assets/734200/5b8b9f2a-e3ee-467b-a398-95f78d175fbb">

There are no extra points with INTERSECTION, though:

<img width="250" alt="image" src="https://github.com/gkjohnson/three-bvh-csg/assets/734200/632798d9-251e-4dcb-990b-1d77d9fbb5e2">

It looks like this doesn't happen with either of the "HOLLOW" operations, either. So this at least helps narrow down which point in the operation these points are being generated from. I'll have to dig in more later

**Comment by gkjohnson** [comment]
It looks like this has been happening all the way back to v0.0.3 (didn't check earlier versions) with the SUBTRACTION operation.

However with the ADDITION operation this only started happening in v0.0.12. The extra points were not present in v0.0.11.

**Comment by gkjohnson** [comment]
It looks like this is occurring because the provided geometry contains degenerate triangles with an area of 0, 0, 0 causing the barycoordinate calculations to be incorrect. I think by some measures this may be at odds with the idea that a geometry needs to be watertight / two-manifold but this shouldn't be too big of an issue to handle.

**Comment by JakeDluhy** [comment]
Thanks so much for jumping on this!
