### ISSUE TITLE
Result object of csg evaluator doesn't have textures

### ISSUE THREAD

**Issue by pceeee** [gkjohnson/three-bvh-csg#201]
Hi, my mesh "sportello" has a texture, but "resultObject" takes only the primary color from the texture, is it possibile to apply the texture to the result of the csg evaluator?
I have tried applying the texture directly to "resultObject" using the map: texture or material.map = texture, but i get the same result.
```
    if ( needsUpdate ) {

        needsUpdate = false;

        sportello.updateMatrixWorld();
        foro.updateMatrixWorld();
        foro2.updateMatrixWorld();
        foro3.updateMatrixWorld();
        foro4.updateMatrixWorld();
        divisore.updateMatrixWorld();

	let finalBrush = brushes[0];
        csgEvaluator.useGroups = params.useGroups;
        csgEvaluator.consolidateGroups = params.consolidateGroups;
		
	for (let i = 1, l = brushes.length; i < l; i++) {
		  const b = brushes[i];
		  finalBrush = csgEvaluator.evaluate(finalBrush, b, ADDITION);
		  finalBrush.material = foro.material;
	}
	csgEvaluator.evaluate(sportello, finalBrush, params.operation, resultObject);
		
        resultObject.material = materialMap.get(sportello.material);

        if ( enableDebugTelemetry ) {

            edgesHelper.setEdges( csgEvaluator.debug.intersectionEdges );

            trisHelper.setTriangles( [
                ...csgEvaluator.debug.triangleIntersectsA.getTrianglesAsArray(),
                ...csgEvaluator.debug.triangleIntersectsA.getIntersectionsAsArray()
            ] );

        }
    }
```

**Comment by gkjohnson** [comment]
Please provide a live example of what you're having issues with.

**Comment by pceeee** [comment]
The "resultObject" should have the material of the borders, but it seems that only the primary color from the texture is being taken

![Screenshot 2024-02-12 alle 09 35 24](https://github.com/gkjohnson/three-bvh-csg/assets/76217503/871e281d-46c1-49c5-b472-0d8549bbde77)
![Screenshot 2024-02-12 alle 09 35 43](https://github.com/gkjohnson/three-bvh-csg/assets/76217503/82370159-37f8-4d15-84b9-1fd48833640c)
![Screenshot 2024-02-12 alle 09 35 51](https://github.com/gkjohnson/three-bvh-csg/assets/76217503/ee047e62-590e-4c03-a5d2-a93a685c4887)
![Screenshot 2024-02-12 alle 09 35 57](https://github.com/gkjohnson/three-bvh-csg/assets/76217503/0299e552-c15c-4094-a2c2-4fc5dd02a4d9)

**Comment by gkjohnson** [comment]
This is not a live example. Please make an editable example using jsfiddle, codesandbox, etc.

**Comment by pceeee** [comment]
[https://jsfiddle.net/lmigani/bthp50v7/38/](https://jsfiddle.net/lmigani/bthp50v7/38/)

The project base was this: [https://gkjohnson.github.io/three-bvh-csg/examples/bundle/simple.html](https://gkjohnson.github.io/three-bvh-csg/examples/bundle/simple.html)

**Comment by pceeee** [comment]
This is the texture
![Uploading wood.jpg…]()

**Comment by gkjohnson** [comment]
Your demo page does not work. Have you tested it? I'm happy to take a look but I'm not planning to spend my time fixing your broken demonstration code just so I can understand your issue. If you'd like help you need to make effort to you need to provide a live, working demonstration of the issue, as I've asked for twice now.

**Comment by pceeee** [comment]
Sorry for the inconvenience, it's working now.

[https://jsfiddle.net/lmigani/52afyg7z/3/](https://jsfiddle.net/lmigani/52afyg7z/3/)

**Comment by gkjohnson** [comment]
You're removing the UVs from the brush:

```js
    csgEvaluator.attributes = [ 'position', 'normal' ]; // make sure "uv" is here
```
