### ISSUE TITLE
brush geometry not expected after save/load

### ISSUE THREAD

**Issue by winman** [gkjohnson/three-bvh-csg#63]
![image](https://user-images.githubusercontent.com/1702606/187057180-4a2c58ee-fc35-43c1-8cae-c6b54f949c61.png)
after save/load the brush geometry as json format, it appears some weird black lines. i wonder how to get rid of this?

thanks for any help!

**Comment by winman** [comment]
maybe this is the cause? when i evaluate/operate these brushes, errmsg occurs a lot like this:

ExtendedTriangle.js:222 ExtendedTriangle.intersectsTriangle: Triangles are coplanar which does not support an output edge. Setting edge to 0, 0, 0.

**Comment by gkjohnson** [comment]
This looks like an issue with the threejs json format which is out of my control. I'd recommend looking into the serialized version of the geometry to make sure it all looks right, first. A live example of the issue would help.

**Comment by gkjohnson** [comment]
Closing this for now - feel free to reopen once you've determined whether this is a three.js or csg issue.
