### ISSUE TITLE
Property 'customProgramCacheKey' in type 'GridMaterial' is not assignable to the same property in base type 'MeshPhongMaterial'

### ISSUE THREAD

**Issue by kirevdokimov** [gkjohnson/three-bvh-csg#66]
```
Property 'customProgramCacheKey' in type 'GridMaterial' is not assignable to the same property in base type 'MeshPhongMaterial'.
  Type '() => boolean' is not assignable to type '() => string'.
    Type 'boolean' is not assignable to type 'string'
```

**Comment by gkjohnson** [comment]
Can you please provide more context? Where is this failing?

**Comment by kirevdokimov** [comment]
It's not failing while you doing it typeless, but if you check types (via typescript cli for example), it's incompatible to each other. Not a crucial thing in general, but a good thing to fix and an important thing to make appropriate types for #67
