### ISSUE TITLE
Missing Triangle

### ISSUE THREAD

**Issue by gkjohnson** [gkjohnson/three-bvh-csg#69]
In the [hierarchy](https://gkjohnson.github.io/three-bvh-csg/examples/bundle/hierarchy.html) demo.

![image](https://user-images.githubusercontent.com/734200/188779539-206fa9d2-e6a2-4d9d-bbe0-fab8187f5285.png)

_Edit:_

This looks like it's a result of incorrect coplanar operation results - specifically with the "frame" component.

<img width="496" alt="image" src="https://user-images.githubusercontent.com/734200/212243110-36333d1c-9691-4c53-b088-3203f3e9698b.png">

**Comment by AngyDev** [comment]
Hi, I tried several changes, but if I set the `width` of the first frame from 2 to 2.1, the issue disappears. 
I don't understand why, but can it be a solution?

**Comment by gkjohnson** [comment]
This issue is a bit trickier - adjusting the geometry itself could avoid the problem but ideally the CSG operations should never result in a mesh hole regardless of the shape. So there's something going on in the numerical robustness or something of the CSG computations. I'd like to get #68 and #51 going to help make it easier to track these issues down and fix them.
