### ISSUE TITLE
Add utility for determining geometric volume

### ISSUE THREAD

**Issue by gkjohnson** [gkjohnson/three-bvh-csg#76]
Related to https://github.com/ifcjs/hello-world/issues/7

[StackOverflow link to implementation overview](
https://stackoverflow.com/questions/1406029/how-to-calculate-the-volume-of-a-3d-mesh-object-the-surface-of-which-is-made-up).

**Requirements**
- Add utility function for determining volume of geometry.
- Add demo showing intersection volume in cubic meters.

**Comment by gkjohnson** [comment]
cc @aka-blackboots - this seemed relevant to your clash detection contribution to IFCjs. With CSG + volume computation you could determine that amount of mesh penetration.

**Comment by aka-blackboots** [comment]
@gkjohnson, will try to look into the implementation. Thanks!
