### ISSUE TITLE
Documentation: Update docs to include note about manifold meshes.

### ISSUE THREAD

**Issue by Ceyhun-Wipelot** [gkjohnson/three-bvh-csg#85]
Hi,
Using `BufferGeometryUtils.MergeGeometry()` on intersected geometries and using that merged geometry with csg operations results with buged faces and missing triangles.

I created this sandbox to demonstrade:
https://codesandbox.io/s/throbbing-breeze-f4hj9p?file=/src/App.js
In this sandbox you can see that results don't have faces along x axis.

**Comment by gkjohnson** [comment]
Thanks for the report! Do you mind making a simplified demonstration that doesn't use React and just uses a minimal number of geometries and operations to show the issue?

**Comment by Ceyhun-Wipelot** [comment]
> Thanks for the report! Do you mind making a simplified demonstration that doesn't use React and just uses a minimal number of geometries and operations to show the issue?

Sure, Here in this sandbox i created without react and using only box geometries:
https://codesandbox.io/s/csg-bug-mergegeometries-zxe2s3?file=/src/index.js

**Comment by gkjohnson** [comment]
As a requirement the meshes that are being used for CSG must be two-manifold - as in no intersecting faces and water tight. With the way you're merging meshes you do not wind up with a two-manifold mesh (see the boxes intersecting). If you move them such that they don't intersect then the CSG works as expected.

I'll update the docs with this information when I get a chance.

**Comment by gkjohnson** [comment]
Ive just added a note in the docs that the brush geometry must be two-manifold to function correctly.

Thanks!

**Comment by Ceyhun-Wipelot** [comment]
Thanks, 
So should I use Addition operator instead of MergeGeometries() on the first brush ?  There is lots of geometries i need to merge first so i am not sure if it will be performant.

**Comment by gkjohnson** [comment]
That's correct. Performance is in progress but if it's an issue please provide an example case so we can see where the issue is.
