### ISSUE TITLE
Issue with overlapping faces on subtraction

### ISSUE THREAD

**Issue by cm-jchen** [gkjohnson/three-bvh-csg#87]
Hi there,

When intersecting with 2 boxes, three-bvh-csg can't really to figure out coplanar. Not sure if this is related to #69. Any suggestion how we can handle this case?

![image](https://user-images.githubusercontent.com/81642626/194680467-7cda9658-b141-4fd8-85d7-a7278891e373.png)

**Comment by cm-jchen** [comment]
![image](https://user-images.githubusercontent.com/81642626/199358122-b66ef5cd-280b-43e1-b5c2-e46c290785d4.png)
I think the COPLANAR Case is just not handled. If I add this line 268, it solves this but it will create triangles on the two side of the box.

**Comment by cm-jchen** [comment]
Not sure if this PR will solve most of the case, but comparing the normal from the planes to determine whether is should be adding a triangle or skipping a triangle

**Comment by shiningapostar** [comment]
Hello, Did fix this issue?
