### ISSUE TITLE
Cylindrical SUBTRACTION, triangular faces loses

### ISSUE THREAD

**Issue by Sea-DH1** [gkjohnson/three-bvh-csg#88]
Try to use CylinderGeometry to do subtraction on the surface of the model, and the result is as shown in the figure.
![image](https://user-images.githubusercontent.com/26751491/194697004-a6f7bbe3-9a13-4472-b60a-efb576d263fe.png)

**Comment by manthrax** [comment]
If you set the material.side = THREE.DoubleSide are the triangles still missing?

**Comment by Sea-DH1** [comment]
The model material is already set  material.side = THREE.DoubleSide  @manthrax

**Comment by DennisSmolek** [comment]
@Sea-DH1 
I'm not able to replicate, can you make a codesandbox or demo?

**Comment by gkjohnson** [comment]
Without a repro case there's nothing that can be done here, I don't think. We can reopen if a reproduction is provided.
