### ISSUE TITLE
Is this library fixed THREE-CSG when dealing with LatheGeometry/ConeGeometry return incorrect result issue?

### ISSUE THREAD

**Issue by AsDeadAsADodo** [gkjohnson/three-bvh-csg#89]
I see [benchmark](https://github.com/gkjohnson/three-bvh-csg/tree/main/benchmark)/[lib](https://github.com/gkjohnson/three-bvh-csg/tree/main/benchmark/lib) include THREE-CSGMesh
This issue is added before in
[intersecting a box with a cone results in a slice of the surface of the cone instead of a solid object](https://github.com/manthrax/THREE-CSGMesh/issues/10)
I did not test cone , only test LatheGeometry.
```
CSG.toMesh(
    CSG.fromMesh(A).intersect(CSG.fromMesh(B)),
    A.matrix,
    A.material
 );
```
[giladdarshan](https://github.com/giladdarshan) suggest change [Line #73](https://github.com/manthrax/THREE-CSGMesh/blob/master/three-csg.js#L73) to
```
return CSG.fromPolygons(polys.filter(p=>!isNaN(p.plane.normal.x)));
```
This issue still exists , subtract and union both return partial of the LatheGeometry , intersect returns something close to A-A∩B but not exactly A-A∩B 
Is this library fixed THREE-CSG when dealing with LatheGeometry/ConeGeometry return incorrect result issue?

**Comment by AsDeadAsADodo** [comment]
> You'll have to test the case yourself - I have not used the library with lathe geometry.

Is this lib based on THREE-CSG ?

**Comment by gkjohnson** [comment]
It's not - this is a new implementation that enables the performance improvements but there are still quirks.

**Comment by AsDeadAsADodo** [comment]
> quirks

OK , Thanks

**Comment by AsDeadAsADodo** [comment]
> It's not - this is a new implementation that enables the performance improvements but there are still quirks.

OK ， thanks
