### ISSUE TITLE
buildFunctions line 770 countNodes sometimes has undefined property 

### ISSUE THREAD

**Issue by AsDeadAsADodo** [gkjohnson/three-bvh-csg#94]
This is the error stack.
Same two Brush es , sometimes it's ok , sometimes got this error.

```
buildFunctions.js:785 Uncaught TypeError: Cannot read properties of undefined (reading 'count')
    at countNodes (buildFunctions.js:785:13)
    at countNodes (buildFunctions.js:791:15)
    at buildPackedTree (buildFunctions.js:770:19)
    at new MeshBVH (MeshBVH.js:165:18)
    at Brush.prepareGeometry (Brush.js:68:26)
    at Evaluator.evaluate (Evaluator.js:137:5)
    at csg (animationTest.js:767:39)
    at animationTest.js:778:30
```

**Comment by AsDeadAsADodo** [comment]
The only difference between good and error is one of the brushes ' position is random.
There's no other errors.

**Comment by AsDeadAsADodo** [comment]
![图片](https://user-images.githubusercontent.com/38915818/202740870-c37e439d-5b1a-416e-a2ea-d1c7fa8b5f20.png)

**Comment by AsDeadAsADodo** [comment]
![图片](https://user-images.githubusercontent.com/38915818/202743002-6a030ee0-3ad0-40dc-9511-5daf3447d565.png)

`node.count` is `0` , however in `else` snippet , `node.left` and `node.right` are both undefined

**Comment by gkjohnson** [comment]
Please provide a repro case with jsfiddle or something comparable so this can be inspected.

**Comment by AsDeadAsADodo** [comment]
@gkjohnson Sorry for the delay , I tried to build a issue version , but we did lots of commits that day I cant reproduce this error.

I fixed this by reducing the random range , tested like 20+ times . 

> ![图片](https://user-images.githubusercontent.com/38915818/202740870-c37e439d-5b1a-416e-a2ea-d1c7fa8b5f20.png)

I suppose this may help too ? No other errors and warnings .

**Comment by gkjohnson** [comment]
> I fixed this by reducing the random range

Unfortunately I'm not sure what this means. Without a minimal reproduce-able example on something like jsfiddle this isn't possible to debug. The line you're pointing to is in the [three-mesh-bvh](https://github.com/gkjohnson/three-mesh-bvh/) project which is fairly well used and well tested. Without a minimal example it's hard to say whether the problem is in your codebase or not.
